version: '2.3'

services:
  training-mpi-api:
    image: training-mpi-api
    build:
      dockerfile: ./Trainings.OpenMpi.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_ConnectionStrings__TrainingMpiDbContext=Server=host.docker.internal;Port=5433;Database=training-mpi;Uid=postgres;Pwd=postgres;      
    depends_on:
      - db
    ports:
      - '12000:80'
      - '12001:443'

  db:
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres
    ports:
      - 5433:5432
    networks:
      - training-mpi-net

networks:
  training-mpi-net:
    external: true
